version: '3.8'

services:
  judgeserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: judgeserver-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - .env:/app/.env
      - ./generated_csv:/app/generated_csv
